### PR TITLE
Time based Asset Reading summary

### PR DESCRIPTION
**Pull request by shariq1501**
Known Issue : Not Mobile Responsive yet.

### CODE REVIEW

**Comment by MonikaSharma06** [comment]
- After selecting time for any assets in the pop up to show the time based summary, the selected time appears in every asset's popup.
- And it should show `No Data`, if data is not available for the selected time.

**Comment by shariq1501** [comment]
@monika-Dianomic Issue fixed. Review now.

**Comment by MonikaSharma06** [comment]
LGTM! @mshariq-nerd 
cc / @praveen-garg

**Comment by shariq1501** [comment]
@praveen-garg  Please review.

**Pull request merged**
